GET  http://localhost:3003/character?name=Deadpool&orderType=DESC

###

PUT http://localhost:3003/character
Content-Type: application/json

{
    "name": "Juggernaut",
    "gender": "MALE",
    "descripition": "O irmão do professor X"
}

###

DELETE http://localhost:3003/character/2